### ISSUE TITLE
JSON property names are strings and should be quoted

### ISSUE THREAD

**Issue by AndyOGo** [AnyRoad/react-json-view-lite#30]
Property names are strings and these are surrounded by quotes.

> A string is a sequence of zero or more Unicode characters, wrapped in double quotes, 
> ...
> string
>   '"' characters '"'
https://www.json.org/json-en.html

**Comment by AnyRoad** [comment]
Some of the similar components (e.g. https://www.npmjs.com/package/react-json-view) display fields surrounded by quotes while some (e.g. https://www.npmjs.com/package/react-json-tree) do not. 
Default JSON viewer in the Firefox also does not show the quotes.

<img width="819" alt="image" src="https://github.com/user-attachments/assets/20b84eb7-41a3-4f7d-aa4a-37a22a36a978">

I think because we do not show the JSON itself but it's representation it is fine to omit the quotes. Or at least it should be optional similar to the `clickToExpandNode` property.

**Comment by AndyOGo** [comment]
Fair point.

Im happy to make the quotes optional.

**Comment by AndyOGo** [comment]
Thank you for accepting my PR.

When do you plan a release?

**Comment by AnyRoad** [comment]
Sorry, was busy for a couple of weeks...
I've released version 2.0.1 today.
Wanted to test more before releasing major version (quite big changes related to the a11y support from another PR).

**Comment by AndyOGo** [comment]
Thx @AnyRoad
